language: node_js
node_js:
- lts/boron
- node
os:
- linux
dist: trusty
script:
- bash <(curl -s https://raw.githubusercontent.com/wooorm/atom-travis/master/install.sh)
- export DISPLAY=":99"
- npm test
